### ISSUE TITLE
Signature nitpick

### ISSUE THREAD

**Issue by Plecra** [Lokathor/gl46#2]
```rust
pub unsafe fn load_from(f: &dyn Fn(*const u8) -> *const c_void) -> Result<Self, &'static str>;
```
It looks like this function doesn't really need to use a trait object, and more closely resembles a
```rust
pub unsafe fn load_from(f: impl FnMut(*const u8) -> *const c_void) -> Result<Self, &'static str>;
```
(ofc it could be arbitrarily restricted to `Fn` if that seems safer, but I don't see why we would)

**Comment by Lokathor** [comment]
The dyn part means there's one function instead of generic instances of fhe function. it's like 1% goofy to call but saves on rebuild times.

**Comment by Plecra** [comment]
Would it make sense to use the inner-function (like std's `AsRef<Path>` functions) pattern here to have the same improvement in build times?

**Comment by Lokathor** [comment]
maybe? this is already a very simple interface for the user to call, and i think that everything being dyn will give the best compile time already.

**Comment by Plecra** [comment]
I find that most users expect callbacks to work when passed directly (`foo(|| {})`). Ofc it's not that important, but I do think `impl` arguments are typically more idiomatic

**Comment by Lokathor** [comment]
Sure, but the fix is to just do `foo(&||{})` instead.

There should probably be a bit about this in the docs though, now that you mention it.

**Comment by Lokathor** [comment]
@Plecra I hope that the extra bit of docs in https://github.com/Lokathor/gl46/commit/36872579692bb0fc33d440dc5453db7524c4e370 resolves your concern
