### ISSUE TITLE
Links in documentation broken

### ISSUE THREAD

**Issue by Plecra** [Lokathor/gl46#4]
```rust
//! [glutin]: (https://docs.rs/glutin/0.26.0/glutin)
```

Link references shouldn't include brackets

**Comment by Lokathor** [comment]
that [glutin] part links to another link above that uses [glutin] as the target. when rendered together markdown will combine the two link parts into one: https://docs.rs/gl46/0.2.0/gl46/#gl_get_proc_address

**Comment by Plecra** [comment]
Hm... the links on docs.rs redirect me to https://docs.rs/gl46/0.2.0/gl46/(https://docs.rs/glutin/0.26.0/glutin), which 404s. Is this is configuration problem on my end?

**Comment by Lokathor** [comment]
oh, uh, no I'm getting the same thing now that you mention it. i think rustdoc is generating bad links.

**Comment by Lokathor** [comment]
oh my rustdoc expert says that the ( ) on the links is the problem, so i understand your comment now about the extra brackets. I'll try to fix this today.
